管理者ダッシュボードの実装 #14
mickhosokawa/seek pull request #15
Opened 2022-10-30 11:10 UTC by mickhosokawa

管理者ログイン後にダッシュボードに遷移する機能を実装しました。

2022-10-30 22:06 UTC, aokitashipro requested changes
レビューしましたのでご確認をお願いいたします。

2022-10-30 22:06 UTC, aokitashipro commented on app/Models/CompanyInfo.php
> +    public function company(){
slackでも書いたんですが 1対1 にするか 1対多にするかで変わってきます。

2022-10-30 22:06 UTC, aokitashipro commented on app/Models/Company.php
> +use App\Models\CompanyInfo as ModelsCompanyInfo;
as ModelsCompanyInfo と別名にしてるのは何か理由ありましたでしょうか。

2022-10-31 05:34 UTC, mickhosokawa commented on app/Models/CompanyInfo.php
> +    public function company(){
hasOneに修正しました。また、HumanResourceにはbelongToメソッド

2022-10-31 05:34 UTC, mickhosokawa commented on app/Models/Company.php
> +use App\Models\CompanyInfo as ModelsCompanyInfo;
特にありません。記述ミスです。

2022-10-31 06:11 UTC, aokitashipro commented on app/Models/HumanResource.php
> +class Company extends Model
PSR-4的に、
ファイル名とクラス名は合わせる必要があるので、
class HumanResource でお願いします。

2022-10-31 06:12 UTC, mickhosokawa commented on app/Models/HumanResource.php
> +class Company extends Model
すみません。確認漏れでした。。。
すぐ直します。

2022-10-31 06:20 UTC, mickhosokawa commented on app/Models/HumanResource.php
> +class Company extends Model
すみません、自分のミスで上手くコミットが反映されていなかったみたいです。
こちらでclass名とファイル名を合わせました。
ご確認をお願いいたします。
https://github.com/mickhosokawa/seek/pull/15/commits/3677cfd16852b8a0aba2a4e6b9d64f77494fd779

2022-10-31 06:26 UTC, aokitashipro approved these changes
ご対応ありがとうございます。

2022-10-31 06:26 UTC, merged