Edit job offer
mickhosokawa/seek pull request #24
Opened 2022-11-24 14:15 UTC by mickhosokawa

求人情報の更新処理と削除処理を実装しました。

2022-11-25 04:33 UTC, aokitashipro requested changes
deleteメソッドが動いてないように見えるのでご確認お願いいたします。

2022-11-25 04:33 UTC, aokitashipro commented on resources/views/company/jobs/edit.blade.php
> +                <button type="submit" class="flex mx-auto text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg">Delete</button>
試しにdeleteボタン押したらupdate is successed と表示されたので
deleteメソッドは実行されていないように見えます。

2022-11-26 00:14 UTC, mickhosokawa commented on resources/views/company/jobs/edit.blade.php
> +                <button type="submit" class="flex mx-auto text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg">Delete</button>
こちら修正をおこないました。
formタグをedit、delete両方に付けて対応しました。

2022-11-26 00:19 UTC, aokitashipro commented on resources/views/company/jobs/edit.blade.php
> +                  <button type="submit" class="flex mx-auto text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg">Delete</button>
formタグの組み方がちょっと違って、
update前後で囲むのと、deleteで囲む必要があります。
今130行目に</form>が残っているので修正お願いします。

2022-11-26 00:26 UTC, aokitashipro commented on resources/views/company/jobs/edit.blade.php
> +                  <button type="submit" class="flex mx-auto text-white bg-pink-500 border-0 py-2 px-8 focus:outline-none hover:bg-pink-600 rounded text-lg">Delete</button>
まだ違いますね、
19行目に<form>があり、121行目にも<form>があるので121の<form>も不要ですね。

2022-11-26 01:40 UTC, merged